/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.banba.digitalclock;

public final class R {
    public static final class anim {
        public static final int card_flip_left_in=0x7f040000;
        public static final int card_flip_left_out=0x7f040001;
        public static final int card_flip_right_in=0x7f040002;
        public static final int card_flip_right_out=0x7f040003;
        public static final int slide_in_top=0x7f040004;
        public static final int slide_out_bottom=0x7f040005;
        public static final int spin=0x7f040006;
    }
    public static final class array {
        public static final int date_format_arr=0x7f060002;
        public static final int date_range_arr=0x7f060003;
        public static final int time_option_arr=0x7f060000;
        public static final int val_arr=0x7f060001;
    }
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int dial=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int hand_hour=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int hand_minute=0x7f010002;
    }
    public static final class color {
        public static final int holo_blue_bright=0x7f070000;
        public static final int holo_blue_light=0x7f070001;
    }
    public static final class dimen {
        public static final int analog_clock_size=0x7f08000b;
        public static final int clock_date_text_size=0x7f080008;
        public static final int clock_date_top_margin=0x7f080009;
        public static final int clock_left_margin=0x7f080003;
        public static final int clock_margin_offset=0x7f08000a;
        public static final int clock_side_padding=0x7f080004;
        /**  We use dp units instead of sp since the lock screen is a fixed size area. 
         */
        public static final int clock_text_size_large=0x7f080006;
        public static final int clock_text_size_small=0x7f080007;
        public static final int color_grid_circle_size=0x7f08001c;
        public static final int color_grid_extra_padding=0x7f08001d;
        public static final int color_grid_item_size=0x7f08001b;
        public static final int daydream_extensions_width=0x7f08001e;
        public static final int digitHeight=0x7f080002;
        public static final int drag_grip_ridge_gap=0x7f080019;
        public static final int drag_grip_ridge_size=0x7f080018;
        public static final int extension_collapsed_text_size_single_line=0x7f080010;
        public static final int extension_collapsed_text_size_two_line=0x7f080011;
        public static final int extension_collapsed_vert_padding=0x7f080005;
        public static final int extension_expanded_body_text_size=0x7f080013;
        public static final int extension_expanded_title_text_size=0x7f080012;
        public static final int extension_icon_collapsed_size=0x7f080015;
        public static final int extension_icon_expanded_size=0x7f080014;
        public static final int list_fading_edge_length=0x7f08001a;
        public static final int min_expanded_height=0x7f080017;
        public static final int min_expanded_height_lock_screen=0x7f080016;
        public static final int mini_clock_date_text_size=0x7f08000e;
        public static final int mini_clock_date_top_padding=0x7f08000f;
        /**  Mini mode for other layouts 
         */
        public static final int mini_clock_text_size_large=0x7f08000c;
        public static final int mini_clock_text_size_small=0x7f08000d;
        public static final int widget_margin=0x7f080000;
        public static final int widget_text_height=0x7f080001;
    }
    public static final class drawable {
        public static final int bottom_0_0=0x7f020000;
        public static final int bottom_0_1=0x7f020001;
        public static final int bottom_0_2=0x7f020002;
        public static final int bottom_0_3=0x7f020003;
        public static final int bottom_1_0=0x7f020004;
        public static final int bottom_1_1=0x7f020005;
        public static final int bottom_1_2=0x7f020006;
        public static final int bottom_1_3=0x7f020007;
        public static final int bottom_2_0=0x7f020008;
        public static final int bottom_2_1=0x7f020009;
        public static final int bottom_2_2=0x7f02000a;
        public static final int bottom_2_3=0x7f02000b;
        public static final int bottom_3_0=0x7f02000c;
        public static final int bottom_3_1=0x7f02000d;
        public static final int bottom_3_2=0x7f02000e;
        public static final int bottom_3_3=0x7f02000f;
        public static final int bottom_4_0=0x7f020010;
        public static final int bottom_4_1=0x7f020011;
        public static final int bottom_4_2=0x7f020012;
        public static final int bottom_4_3=0x7f020013;
        public static final int bottom_5_0=0x7f020014;
        public static final int bottom_5_1=0x7f020015;
        public static final int bottom_5_2=0x7f020016;
        public static final int bottom_5_3=0x7f020017;
        public static final int bottom_6_0=0x7f020018;
        public static final int bottom_6_1=0x7f020019;
        public static final int bottom_6_2=0x7f02001a;
        public static final int bottom_6_3=0x7f02001b;
        public static final int bottom_7_0=0x7f02001c;
        public static final int bottom_7_1=0x7f02001d;
        public static final int bottom_7_2=0x7f02001e;
        public static final int bottom_7_3=0x7f02001f;
        public static final int bottom_8_0=0x7f020020;
        public static final int bottom_8_1=0x7f020021;
        public static final int bottom_8_2=0x7f020022;
        public static final int bottom_8_3=0x7f020023;
        public static final int bottom_9_0=0x7f020024;
        public static final int bottom_9_1=0x7f020025;
        public static final int bottom_9_2=0x7f020026;
        public static final int bottom_9_3=0x7f020027;
        public static final int clock_dial=0x7f020028;
        public static final int clock_hour=0x7f020029;
        public static final int clock_minute=0x7f02002a;
        public static final int clockgoog_minute=0x7f02002b;
        public static final int ic_launcher=0x7f02002c;
        public static final int icon=0x7f02002d;
        public static final int overscroll_edge=0x7f02002e;
        public static final int overscroll_glow=0x7f02002f;
        public static final int textclockwidget=0x7f020030;
        public static final int top_0_0=0x7f020031;
        public static final int top_0_1=0x7f020032;
        public static final int top_0_2=0x7f020033;
        public static final int top_1_0=0x7f020034;
        public static final int top_1_1=0x7f020035;
        public static final int top_1_2=0x7f020036;
        public static final int top_2_0=0x7f020037;
        public static final int top_2_1=0x7f020038;
        public static final int top_2_2=0x7f020039;
        public static final int top_3_0=0x7f02003a;
        public static final int top_3_1=0x7f02003b;
        public static final int top_3_2=0x7f02003c;
        public static final int top_4_0=0x7f02003d;
        public static final int top_4_1=0x7f02003e;
        public static final int top_4_2=0x7f02003f;
        public static final int top_5_0=0x7f020040;
        public static final int top_5_1=0x7f020041;
        public static final int top_5_2=0x7f020042;
        public static final int top_6_0=0x7f020043;
        public static final int top_6_1=0x7f020044;
        public static final int top_6_2=0x7f020045;
        public static final int top_7_0=0x7f020046;
        public static final int top_7_1=0x7f020047;
        public static final int top_7_2=0x7f020048;
        public static final int top_8_0=0x7f020049;
        public static final int top_8_1=0x7f02004a;
        public static final int top_8_2=0x7f02004b;
        public static final int top_9_0=0x7f02004c;
        public static final int top_9_1=0x7f02004d;
        public static final int top_9_2=0x7f02004e;
        public static final int widget_background=0x7f02004f;
    }
    public static final class id {
        public static final int analogClock=0x7f0c0000;
        public static final int button1=0x7f0c000f;
        public static final int clock_target=0x7f0c0019;
        public static final int cwClock=0x7f0c0008;
        public static final int date_container=0x7f0c001b;
        public static final int daydream_container=0x7f0c0005;
        public static final int daydream_root=0x7f0c0004;
        public static final int dcHour0=0x7f0c0009;
        public static final int dcHour1=0x7f0c000a;
        public static final int dcMinute0=0x7f0c000b;
        public static final int dcMinute1=0x7f0c000c;
        public static final int dcSecond0=0x7f0c000d;
        public static final int dcSecond1=0x7f0c000e;
        public static final int extensions_container=0x7f0c0007;
        public static final int extensions_scroller=0x7f0c0006;
        public static final int heading_tv=0x7f0c0012;
        public static final int hours=0x7f0c0001;
        public static final int imageButton1=0x7f0c0013;
        public static final int imageButton2=0x7f0c0014;
        public static final int imageButton3=0x7f0c0015;
        public static final int imageButton4=0x7f0c0017;
        public static final int list_view=0x7f0c0018;
        public static final int menu_bar=0x7f0c0011;
        public static final int minutes=0x7f0c0003;
        public static final int range_tv=0x7f0c0016;
        public static final int status=0x7f0c0010;
        public static final int tens=0x7f0c0002;
        public static final int time_container=0x7f0c001a;
    }
    public static final class integer {
        public static final int animationSpeed=0x7f090000;
        public static final int card_flip_time_full=0x7f090001;
        public static final int card_flip_time_half=0x7f090002;
    }
    public static final class layout {
        public static final int analog_appwidget=0x7f030000;
        public static final int analogclock=0x7f030001;
        public static final int appwidget=0x7f030002;
        public static final int daydream=0x7f030003;
        public static final int digitalclock=0x7f030004;
        public static final int inc_flipclock=0x7f030005;
        public static final int keyguard=0x7f030006;
        public static final int main=0x7f030007;
        public static final int set_alarm=0x7f030008;
        public static final int textclock_widget=0x7f030009;
        public static final int widget_include_clock=0x7f03000a;
    }
    public static final class string {
        public static final int app_name=0x7f0a0171;
        public static final int fa_adjust=0x7f0a003e;
        public static final int fa_adn=0x7f0a014c;
        public static final int fa_align_center=0x7f0a0034;
        public static final int fa_align_justify=0x7f0a0036;
        public static final int fa_align_left=0x7f0a0033;
        public static final int fa_align_right=0x7f0a0035;
        public static final int fa_ambulance=0x7f0a00de;
        public static final int fa_anchor=0x7f0a011d;
        public static final int fa_android=0x7f0a0157;
        public static final int fa_angle_double_down=0x7f0a00e7;
        public static final int fa_angle_double_left=0x7f0a00e4;
        public static final int fa_angle_double_right=0x7f0a00e5;
        public static final int fa_angle_double_up=0x7f0a00e6;
        public static final int fa_angle_down=0x7f0a00eb;
        public static final int fa_angle_left=0x7f0a00e8;
        public static final int fa_angle_right=0x7f0a00e9;
        public static final int fa_angle_up=0x7f0a00ea;
        public static final int fa_apple=0x7f0a0155;
        public static final int fa_archive=0x7f0a0162;
        public static final int fa_arrow_circle_down=0x7f0a00a1;
        public static final int fa_arrow_circle_left=0x7f0a009e;
        public static final int fa_arrow_circle_o_down=0x7f0a0019;
        public static final int fa_arrow_circle_o_left=0x7f0a016a;
        public static final int fa_arrow_circle_o_right=0x7f0a0169;
        public static final int fa_arrow_circle_o_up=0x7f0a001a;
        public static final int fa_arrow_circle_right=0x7f0a009f;
        public static final int fa_arrow_circle_up=0x7f0a00a0;
        public static final int fa_arrow_down=0x7f0a005d;
        public static final int fa_arrow_left=0x7f0a005a;
        public static final int fa_arrow_right=0x7f0a005b;
        public static final int fa_arrow_up=0x7f0a005c;
        public static final int fa_arrows=0x7f0a0043;
        public static final int fa_arrows_alt=0x7f0a00a7;
        public static final int fa_arrows_h=0x7f0a0077;
        public static final int fa_arrows_v=0x7f0a0076;
        public static final int fa_asterisk=0x7f0a0063;
        public static final int fa_backward=0x7f0a0046;
        public static final int fa_ban=0x7f0a0059;
        public static final int fa_bar_chart_o=0x7f0a0078;
        public static final int fa_barcode=0x7f0a0027;
        public static final int fa_bars=0x7f0a00b1;
        public static final int fa_beer=0x7f0a00e1;
        public static final int fa_bell=0x7f0a0098;
        public static final int fa_bell_o=0x7f0a00d8;
        public static final int fa_bitbucket=0x7f0a014d;
        public static final int fa_bitbucket_square=0x7f0a014e;
        public static final int fa_bold=0x7f0a002f;
        public static final int fa_bolt=0x7f0a00cd;
        public static final int fa_book=0x7f0a002a;
        public static final int fa_bookmark=0x7f0a002b;
        public static final int fa_bookmark_o=0x7f0a008e;
        public static final int fa_briefcase=0x7f0a00a6;
        public static final int fa_btc=0x7f0a0138;
        public static final int fa_bug=0x7f0a0163;
        public static final int fa_building_o=0x7f0a00dc;
        public static final int fa_bullhorn=0x7f0a0097;
        public static final int fa_bullseye=0x7f0a011f;
        public static final int fa_calendar=0x7f0a006c;
        public static final int fa_calendar_o=0x7f0a0113;
        public static final int fa_camera=0x7f0a002d;
        public static final int fa_camera_retro=0x7f0a007b;
        public static final int fa_caret_down=0x7f0a00be;
        public static final int fa_caret_left=0x7f0a00c0;
        public static final int fa_caret_right=0x7f0a00c1;
        public static final int fa_caret_square_o_down=0x7f0a012e;
        public static final int fa_caret_square_o_left=0x7f0a016b;
        public static final int fa_caret_square_o_right=0x7f0a0130;
        public static final int fa_caret_square_o_up=0x7f0a012f;
        public static final int fa_caret_up=0x7f0a00bf;
        public static final int fa_certificate=0x7f0a0099;
        public static final int fa_chain_broken=0x7f0a0108;
        public static final int fa_check=0x7f0a000c;
        public static final int fa_check_circle=0x7f0a0053;
        public static final int fa_check_circle_o=0x7f0a0058;
        public static final int fa_check_square=0x7f0a0129;
        public static final int fa_check_square_o=0x7f0a0042;
        public static final int fa_chevron_circle_down=0x7f0a011a;
        public static final int fa_chevron_circle_left=0x7f0a0117;
        public static final int fa_chevron_circle_right=0x7f0a0118;
        public static final int fa_chevron_circle_up=0x7f0a0119;
        public static final int fa_chevron_down=0x7f0a0071;
        public static final int fa_chevron_left=0x7f0a004e;
        public static final int fa_chevron_right=0x7f0a004f;
        public static final int fa_chevron_up=0x7f0a0070;
        public static final int fa_circle=0x7f0a00f4;
        public static final int fa_circle_o=0x7f0a00f0;
        public static final int fa_clipboard=0x7f0a00d0;
        public static final int fa_clock_o=0x7f0a0016;
        public static final int fa_cloud=0x7f0a00aa;
        public static final int fa_cloud_download=0x7f0a00d3;
        public static final int fa_cloud_upload=0x7f0a00d4;
        public static final int fa_code=0x7f0a0101;
        public static final int fa_code_fork=0x7f0a0107;
        public static final int fa_coffee=0x7f0a00d9;
        public static final int fa_cog=0x7f0a0012;
        public static final int fa_cogs=0x7f0a007d;
        public static final int fa_columns=0x7f0a00c2;
        public static final int fa_comment=0x7f0a006e;
        public static final int fa_comment_o=0x7f0a00cb;
        public static final int fa_comments=0x7f0a007e;
        public static final int fa_comments_o=0x7f0a00cc;
        public static final int fa_compass=0x7f0a012d;
        public static final int fa_compress=0x7f0a0060;
        public static final int fa_credit_card=0x7f0a0094;
        public static final int fa_crop=0x7f0a0106;
        public static final int fa_crosshairs=0x7f0a0056;
        public static final int fa_css3=0x7f0a011c;
        public static final int fa_cutlery=0x7f0a00da;
        public static final int fa_desktop=0x7f0a00ec;
        public static final int fa_dot_circle_o=0x7f0a016c;
        public static final int fa_download=0x7f0a0018;
        public static final int fa_dribbble=0x7f0a0159;
        public static final int fa_dropbox=0x7f0a0148;
        public static final int fa_eject=0x7f0a004d;
        public static final int fa_ellipsis_h=0x7f0a0120;
        public static final int fa_ellipsis_v=0x7f0a0121;
        public static final int fa_envelope=0x7f0a00c6;
        public static final int fa_envelope_o=0x7f0a0003;
        public static final int fa_eraser=0x7f0a010e;
        public static final int fa_eur=0x7f0a0131;
        public static final int fa_exchange=0x7f0a00d2;
        public static final int fa_exclamation=0x7f0a010b;
        public static final int fa_exclamation_circle=0x7f0a0064;
        public static final int fa_exclamation_triangle=0x7f0a006a;
        public static final int fa_expand=0x7f0a005f;
        public static final int fa_external_link=0x7f0a0086;
        public static final int fa_external_link_square=0x7f0a012b;
        public static final int fa_eye=0x7f0a0068;
        public static final int fa_eye_slash=0x7f0a0069;
        public static final int fa_facebook=0x7f0a0091;
        public static final int fa_facebook_square=0x7f0a007a;
        public static final int fa_fast_backward=0x7f0a0045;
        public static final int fa_fast_forward=0x7f0a004b;
        public static final int fa_female=0x7f0a015d;
        public static final int fa_fighter_jet=0x7f0a00e0;
        public static final int fa_file=0x7f0a0139;
        public static final int fa_file_o=0x7f0a0015;
        public static final int fa_file_text=0x7f0a013a;
        public static final int fa_file_text_o=0x7f0a00db;
        public static final int fa_files_o=0x7f0a00ad;
        public static final int fa_film=0x7f0a0008;
        public static final int fa_filter=0x7f0a00a5;
        public static final int fa_fire=0x7f0a0067;
        public static final int fa_fire_extinguisher=0x7f0a0114;
        public static final int fa_flag=0x7f0a0021;
        public static final int fa_flag_checkered=0x7f0a00ff;
        public static final int fa_flag_o=0x7f0a00fe;
        public static final int fa_flask=0x7f0a00ab;
        public static final int fa_flickr=0x7f0a014b;
        public static final int fa_floppy_o=0x7f0a00af;
        public static final int fa_folder=0x7f0a0074;
        public static final int fa_folder_o=0x7f0a00f7;
        public static final int fa_folder_open=0x7f0a0075;
        public static final int fa_folder_open_o=0x7f0a00f8;
        public static final int fa_font=0x7f0a002e;
        public static final int fa_forward=0x7f0a004a;
        public static final int fa_foursquare=0x7f0a015b;
        public static final int fa_frown_o=0x7f0a00fa;
        public static final int fa_gamepad=0x7f0a00fc;
        public static final int fa_gavel=0x7f0a00c9;
        public static final int fa_gbp=0x7f0a0132;
        public static final int fa_gift=0x7f0a0065;
        public static final int fa_github=0x7f0a0092;
        public static final int fa_github_alt=0x7f0a00f6;
        public static final int fa_github_square=0x7f0a0089;
        public static final int fa_gittip=0x7f0a015f;
        public static final int fa_glass=0x7f0a0000;
        public static final int fa_globe=0x7f0a00a2;
        public static final int fa_google_plus=0x7f0a00bc;
        public static final int fa_google_plus_square=0x7f0a00bb;
        public static final int fa_h_square=0x7f0a00e2;
        public static final int fa_hand_o_down=0x7f0a009d;
        public static final int fa_hand_o_left=0x7f0a009b;
        public static final int fa_hand_o_right=0x7f0a009a;
        public static final int fa_hand_o_up=0x7f0a009c;
        public static final int fa_hdd_o=0x7f0a0096;
        public static final int fa_headphones=0x7f0a0022;
        public static final int fa_heart=0x7f0a0004;
        public static final int fa_heart_o=0x7f0a0082;
        public static final int fa_home=0x7f0a0014;
        public static final int fa_hospital_o=0x7f0a00dd;
        public static final int fa_html5=0x7f0a011b;
        public static final int fa_inbox=0x7f0a001b;
        public static final int fa_indent=0x7f0a0039;
        public static final int fa_info=0x7f0a010a;
        public static final int fa_info_circle=0x7f0a0055;
        public static final int fa_inr=0x7f0a0134;
        public static final int fa_instagram=0x7f0a014a;
        public static final int fa_italic=0x7f0a0030;
        public static final int fa_jpy=0x7f0a0135;
        public static final int fa_key=0x7f0a007c;
        public static final int fa_keyboard_o=0x7f0a00fd;
        public static final int fa_krw=0x7f0a0137;
        public static final int fa_laptop=0x7f0a00ed;
        public static final int fa_leaf=0x7f0a0066;
        public static final int fa_lemon_o=0x7f0a008b;
        public static final int fa_level_down=0x7f0a0128;
        public static final int fa_level_up=0x7f0a0127;
        public static final int fa_lightbulb_o=0x7f0a00d1;
        public static final int fa_link=0x7f0a00a9;
        public static final int fa_linkedin=0x7f0a00c7;
        public static final int fa_linkedin_square=0x7f0a0084;
        public static final int fa_linux=0x7f0a0158;
        public static final int fa_list=0x7f0a0037;
        public static final int fa_list_alt=0x7f0a001f;
        public static final int fa_list_ol=0x7f0a00b3;
        public static final int fa_list_ul=0x7f0a00b2;
        public static final int fa_location_arrow=0x7f0a0105;
        public static final int fa_lock=0x7f0a0020;
        public static final int fa_long_arrow_down=0x7f0a0151;
        public static final int fa_long_arrow_left=0x7f0a0153;
        public static final int fa_long_arrow_right=0x7f0a0154;
        public static final int fa_long_arrow_up=0x7f0a0152;
        public static final int fa_magic=0x7f0a00b7;
        public static final int fa_magnet=0x7f0a006f;
        public static final int fa_mail_reply_all=0x7f0a0103;
        public static final int fa_male=0x7f0a015e;
        public static final int fa_map_marker=0x7f0a003d;
        public static final int fa_maxcdn=0x7f0a0116;
        public static final int fa_medkit=0x7f0a00df;
        public static final int fa_meh_o=0x7f0a00fb;
        public static final int fa_microphone=0x7f0a0110;
        public static final int fa_microphone_slash=0x7f0a0111;
        public static final int fa_minus=0x7f0a0062;
        public static final int fa_minus_circle=0x7f0a0051;
        public static final int fa_minus_square=0x7f0a0125;
        public static final int fa_minus_square_o=0x7f0a0126;
        public static final int fa_mobile=0x7f0a00ef;
        public static final int fa_money=0x7f0a00bd;
        public static final int fa_moon_o=0x7f0a0161;
        public static final int fa_music=0x7f0a0001;
        public static final int fa_outdent=0x7f0a0038;
        public static final int fa_pagelines=0x7f0a0167;
        public static final int fa_paperclip=0x7f0a00ae;
        public static final int fa_pause=0x7f0a0048;
        public static final int fa_pencil=0x7f0a003c;
        public static final int fa_pencil_square=0x7f0a012a;
        public static final int fa_pencil_square_o=0x7f0a0040;
        public static final int fa_phone=0x7f0a008c;
        public static final int fa_phone_square=0x7f0a008f;
        public static final int fa_picture_o=0x7f0a003b;
        public static final int fa_pinterest=0x7f0a00b9;
        public static final int fa_pinterest_square=0x7f0a00ba;
        public static final int fa_plane=0x7f0a006b;
        public static final int fa_play=0x7f0a0047;
        public static final int fa_play_circle=0x7f0a0123;
        public static final int fa_play_circle_o=0x7f0a001c;
        public static final int fa_plus=0x7f0a0061;
        public static final int fa_plus_circle=0x7f0a0050;
        public static final int fa_plus_square=0x7f0a00e3;
        public static final int fa_plus_square_o=0x7f0a0170;
        public static final int fa_power_off=0x7f0a0010;
        public static final int fa_print=0x7f0a002c;
        public static final int fa_puzzle_piece=0x7f0a010f;
        public static final int fa_qrcode=0x7f0a0026;
        public static final int fa_question=0x7f0a0109;
        public static final int fa_question_circle=0x7f0a0054;
        public static final int fa_quote_left=0x7f0a00f1;
        public static final int fa_quote_right=0x7f0a00f2;
        public static final int fa_random=0x7f0a006d;
        public static final int fa_refresh=0x7f0a001e;
        public static final int fa_renren=0x7f0a0166;
        public static final int fa_repeat=0x7f0a001d;
        public static final int fa_reply=0x7f0a00f5;
        public static final int fa_reply_all=0x7f0a0102;
        public static final int fa_retweet=0x7f0a0072;
        public static final int fa_road=0x7f0a0017;
        public static final int fa_rocket=0x7f0a0115;
        public static final int fa_rss=0x7f0a0095;
        public static final int fa_rss_square=0x7f0a0122;
        public static final int fa_rub=0x7f0a0136;
        public static final int fa_scissors=0x7f0a00ac;
        public static final int fa_search=0x7f0a0002;
        public static final int fa_search_minus=0x7f0a000f;
        public static final int fa_search_plus=0x7f0a000e;
        public static final int fa_share=0x7f0a005e;
        public static final int fa_share_square=0x7f0a012c;
        public static final int fa_share_square_o=0x7f0a0041;
        public static final int fa_shield=0x7f0a0112;
        public static final int fa_shopping_cart=0x7f0a0073;
        public static final int fa_sign_in=0x7f0a0087;
        public static final int fa_sign_out=0x7f0a0083;
        public static final int fa_signal=0x7f0a0011;
        public static final int fa_sitemap=0x7f0a00ce;
        public static final int fa_skype=0x7f0a015a;
        public static final int fa_smile_o=0x7f0a00f9;
        public static final int fa_sort=0x7f0a00c3;
        public static final int fa_sort_alpha_asc=0x7f0a013b;
        public static final int fa_sort_alpha_desc=0x7f0a013c;
        public static final int fa_sort_amount_asc=0x7f0a013d;
        public static final int fa_sort_amount_desc=0x7f0a013e;
        public static final int fa_sort_asc=0x7f0a00c4;
        public static final int fa_sort_desc=0x7f0a00c5;
        public static final int fa_sort_numeric_asc=0x7f0a013f;
        public static final int fa_sort_numeric_desc=0x7f0a0140;
        public static final int fa_spinner=0x7f0a00f3;
        public static final int fa_square=0x7f0a00b0;
        public static final int fa_square_o=0x7f0a008d;
        public static final int fa_stack_exchange=0x7f0a0168;
        public static final int fa_stack_overflow=0x7f0a0149;
        public static final int fa_star=0x7f0a0005;
        public static final int fa_star_half=0x7f0a0081;
        public static final int fa_star_half_o=0x7f0a0104;
        public static final int fa_star_o=0x7f0a0006;
        public static final int fa_step_backward=0x7f0a0044;
        public static final int fa_step_forward=0x7f0a004c;
        public static final int fa_stethoscope=0x7f0a00d6;
        public static final int fa_stop=0x7f0a0049;
        public static final int fa_strikethrough=0x7f0a00b4;
        public static final int fa_subscript=0x7f0a010d;
        public static final int fa_suitcase=0x7f0a00d7;
        public static final int fa_sun_o=0x7f0a0160;
        public static final int fa_superscript=0x7f0a010c;
        public static final int fa_table=0x7f0a00b6;
        public static final int fa_tablet=0x7f0a00ee;
        public static final int fa_tachometer=0x7f0a00ca;
        public static final int fa_tag=0x7f0a0028;
        public static final int fa_tags=0x7f0a0029;
        public static final int fa_tasks=0x7f0a00a4;
        public static final int fa_terminal=0x7f0a0100;
        public static final int fa_text_height=0x7f0a0031;
        public static final int fa_text_width=0x7f0a0032;
        public static final int fa_th=0x7f0a000a;
        public static final int fa_th_large=0x7f0a0009;
        public static final int fa_th_list=0x7f0a000b;
        public static final int fa_thumb_tack=0x7f0a0085;
        public static final int fa_thumbs_down=0x7f0a0142;
        public static final int fa_thumbs_o_down=0x7f0a0080;
        public static final int fa_thumbs_o_up=0x7f0a007f;
        public static final int fa_thumbs_up=0x7f0a0141;
        public static final int fa_ticket=0x7f0a0124;
        public static final int fa_times=0x7f0a000d;
        public static final int fa_times_circle=0x7f0a0052;
        public static final int fa_times_circle_o=0x7f0a0057;
        public static final int fa_tint=0x7f0a003f;
        public static final int fa_trash_o=0x7f0a0013;
        public static final int fa_trello=0x7f0a015c;
        public static final int fa_trophy=0x7f0a0088;
        public static final int fa_truck=0x7f0a00b8;
        public static final int fa_try=0x7f0a016f;
        public static final int fa_tumblr=0x7f0a014f;
        public static final int fa_tumblr_square=0x7f0a0150;
        public static final int fa_twitter=0x7f0a0090;
        public static final int fa_twitter_square=0x7f0a0079;
        public static final int fa_umbrella=0x7f0a00cf;
        public static final int fa_underline=0x7f0a00b5;
        public static final int fa_undo=0x7f0a00c8;
        public static final int fa_unlock=0x7f0a0093;
        public static final int fa_unlock_alt=0x7f0a011e;
        public static final int fa_upload=0x7f0a008a;
        public static final int fa_usd=0x7f0a0133;
        public static final int fa_user=0x7f0a0007;
        public static final int fa_user_md=0x7f0a00d5;
        public static final int fa_users=0x7f0a00a8;
        public static final int fa_video_camera=0x7f0a003a;
        public static final int fa_vimeo_square=0x7f0a016e;
        public static final int fa_vk=0x7f0a0164;
        public static final int fa_volume_down=0x7f0a0024;
        public static final int fa_volume_off=0x7f0a0023;
        public static final int fa_volume_up=0x7f0a0025;
        public static final int fa_weibo=0x7f0a0165;
        public static final int fa_wheelchair=0x7f0a016d;
        public static final int fa_windows=0x7f0a0156;
        public static final int fa_wrench=0x7f0a00a3;
        public static final int fa_xing=0x7f0a0145;
        public static final int fa_xing_square=0x7f0a0146;
        public static final int fa_youtube=0x7f0a0144;
        public static final int fa_youtube_play=0x7f0a0147;
        public static final int fa_youtube_square=0x7f0a0143;
    }
    public static final class style {
        /**  Base application theme. 
 Customize your theme here. 
         */
        public static final int AppTheme=0x7f0b0000;
        public static final int hoursTextDaydream=0x7f0b0003;
        public static final int hoursTextKeyguard=0x7f0b0005;
        public static final int hoursTextWidget=0x7f0b0001;
        public static final int minutesTextDaydream=0x7f0b0004;
        public static final int minutesTextKeyguard=0x7f0b0006;
        public static final int minutesTextWidget=0x7f0b0002;
    }
    public static final class xml {
        public static final int appwidget_info=0x7f050000;
        public static final int prefs=0x7f050001;
        public static final int widget=0x7f050002;
    }
    public static final class styleable {
        /** Attributes that can be used with a AnalogClock.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #AnalogClock_dial com.banba.digitalclock:dial}</code></td><td></td></tr>
           <tr><td><code>{@link #AnalogClock_hand_hour com.banba.digitalclock:hand_hour}</code></td><td></td></tr>
           <tr><td><code>{@link #AnalogClock_hand_minute com.banba.digitalclock:hand_minute}</code></td><td></td></tr>
           </table>
           @see #AnalogClock_dial
           @see #AnalogClock_hand_hour
           @see #AnalogClock_hand_minute
         */
        public static final int[] AnalogClock = {
            0x7f010000, 0x7f010001, 0x7f010002
        };
        /**
          <p>This symbol is the offset where the {@link com.banba.digitalclock.R.attr#dial}
          attribute's value can be found in the {@link #AnalogClock} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.banba.digitalclock:dial
        */
        public static final int AnalogClock_dial = 0;
        /**
          <p>This symbol is the offset where the {@link com.banba.digitalclock.R.attr#hand_hour}
          attribute's value can be found in the {@link #AnalogClock} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.banba.digitalclock:hand_hour
        */
        public static final int AnalogClock_hand_hour = 1;
        /**
          <p>This symbol is the offset where the {@link com.banba.digitalclock.R.attr#hand_minute}
          attribute's value can be found in the {@link #AnalogClock} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.banba.digitalclock:hand_minute
        */
        public static final int AnalogClock_hand_minute = 2;
    };
}
